#!/usr/bin/env bash

printf "Executing XTitle Plugin\n"

[ -f "$RESOURCE_FILE" ] && source "$RESOURCE_FILE"
: "${MODULE_CORE_DIR:=$(dirname $0)}"
. "$MODULE_CORE_DIR/functions"
: "${TMP_DIR:=/tmp}"

check_dependencies nolifebar-xtitle nolifebar-fn-xft

mod_init_vars() {
    ellipsis="…"
    max_length="70"
    dzen2_fonts=("Noto Sans" "Noto Sans CJK JP" "Noto Color Emoji")
}

mod_draw_default() {
    local fifo="$1"
    nolifebar-xtitle | truncate_text > "$fifo"
}

mod_draw_dzen2() {
    local fifo="$1"
    nolifebar-xtitle \
        | truncate_text "$ellipsis" "$max_length" \
        | sed --unbuffered 's/\^/^^/g' \
        | nolifebar-fn-xft "${dzen2_fonts[@]}" \
        > "$fifo"
}

truncate_text() {
    local ellipsis="$1"
    local max_length="$2"

    while IFS= read -r line; do
        local text="$line"
        local text_length="${#text}"

        if [ "$text_length" -le "$max_length" ]; then
            printf "%s\n" "$text"
        else
            local truncated_text="${text:0:$((max_length-1))}"
            printf "%s\n" "${truncated_text}${ellipsis}"
        fi
    done
}

mod_loop() {
    mod_draw "$FIFO_FILE"
}

mod_run
