#!/usr/bin/env bash

printf "Executing CAVA Output Plugin\n"

[ -f "$RESOURCE_FILE" ] && source "$RESOURCE_FILE"
: "${MODULE_CORE_DIR:=$(dirname $0)}"
. "$MODULE_CORE_DIR/functions"
: "${TMP_DIR:=/tmp}"

check_dependencies cava pactl

# shared cava
. "$MODULE_CORE_DIR/sc.functions"

cava_cfg="$TMP_DIR/cava_out.cfg"

mod_init_vars() {
    sc_sensitivity=4400
    sc_framerate=15
    sc_bars=30
    sc_fn_create_file="default_create_config"
}

mod_init_dzen2_vars() {
    sc_bars=30
    sc_padding=1
    sc_height=$((CFG_HEIGHT - 2 * sc_padding))
    sc_additional_bar_params=(
        -text 'Audio-Out'
        -fg_colors "<BAR4>"
    )
}

default_create_config() {
    local config="$1"
    cat << EOF > "$config"
[general]
bars = $sc_bars
sleep_timer = 1
framerate = $sc_framerate

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = $sc_height

channels = mono
mono_option = average

[smoothing]
noise_reduction = 20
EOF

    printf "Cava is configured with
. FPS: %15i
. Bars: %14i\n" "$sc_framerate" "$sc_bars"
}

mod_loop() {
    sc_run_cava_and_print_to_file "$cava_cfg" "$FIFO_FILE"
}

mod_run
