#!/usr/bin/env bash

printf "Executing Nvidia GPU Stats Plugin\n"

[ -f "$RESOURCE_FILE" ] && source "$RESOURCE_FILE"
: "${MODULE_CORE_DIR:=$(dirname $0)}"
. "$MODULE_CORE_DIR/functions"
: "${TMP_DIR:=/tmp}"

check_dependencies nvidia-smi

declare -A gpu_metrics_alert_treshold
declare -A gpu_metrics_fmt
declare -A alerts=() # dictionary of ON/OFF value if value > treshold in gpu_metrics_alert_treshold
declare -A gpu_metrics_value=() # Raw metric values
declare -A gpu_metrics_formatted=() # Formatted metrics

mod_init_vars() {
    interval=1
    gpu_index=0

    additional_render_params=()

    gpu_metrics_alert_treshold=(
        ["fan.speed"]=10        # I want to know when fan is on
        ["power.draw"]=30       # power draw is importent for me
        ["utilization.gpu"]=70
        ["temperature.gpu"]=70
        ["utilization.decoder"]=1
        ["utilization.encoder"]=1
        ["clocks.current.graphics"]=1000
        ["clocks.current.memory"]=1000
    )

    visible_params=(
                    'memory.free' 'memory.used'
                    'fan.speed' 'temperature.gpu'
                    'power.draw' 'utilization.gpu'
                    'clocks.current.memory' 'clocks.current.graphics'
                    'utilization.decoder' 'utilization.encoder'
                   )

    # define how to format metrics
    gpu_metrics_fmt=(
        ["name"]="%s"
        ["fan.speed"]="Fan %3i%%"
        ["power.draw"]="Pwr%4iW"
        ["memory.total"]="Ttl %4iM"
        ["memory.free"]="Fre %4iM"
        ["memory.used"]="Use %4iM"
        ["utilization.gpu"]="GPU %3i%%"
        ["temperature.gpu"]="t  %4i°C"
        ["utilization.decoder"]="Dec %3i%%"
        ["utilization.encoder"]="Enc %3i%%"
        ["clocks.current.graphics"]="P%5iMHz"
        ["clocks.current.memory"]="M%5iMHz"
    )
}

# First arg - fifo file for output
mod_draw_dzen2() {
    local output=""
    dzen2_draw_flags output \
        gpu_metrics_formatted \
        alerts \
        visible_params \
        -label "GPU" \
        "${CFG_DEFAULT_DRAW_FLAG_PARAMS[@]}" \
        -name_size 60 \
        -flag_align _LEFT \
        -flag_x_padding 3 \
        "${additional_render_params[@]}"
    printf "%s\n" "$output"
}

mod_loop() {
    local fifo="$1"

    # blank state
    mod_draw > "$FIFO_FILE"

    nvidia-smi -l "$interval" \
        --query-gpu=index,name,fan.speed,power.draw,memory.total,memory.free,memory.used,utilization.gpu,temperature.gpu,utilization.decoder,utilization.encoder,clocks.current.graphics,clocks.current.memory \
        --format=csv,noheader,nounits \
        | sed --unbuffered 's/, /,/g' \
        | while IFS=, read -r index name fan_speed power_draw memory_total \
                              memory_free memory_used gpu_utilization temperature \
                              decoder encoder clocks_graphics clocks_memory
    do
        if ((index != gpu_index)); then continue; fi
        power_draw="${power_draw%%.*}" # to integer: 24.15 -> 24

        gpu_metrics_value["name"]="$name"
        gpu_metrics_value["fan.speed"]="$fan_speed"
        gpu_metrics_value["power.draw"]="$power_draw"
        gpu_metrics_value["memory.total"]="$memory_total"
        gpu_metrics_value["memory.free"]="$memory_free"
        gpu_metrics_value["memory.used"]="$memory_used"
        gpu_metrics_value["utilization.gpu"]="$gpu_utilization"
        gpu_metrics_value["temperature.gpu"]="$temperature"
        gpu_metrics_value["utilization.decoder"]="$decoder"
        gpu_metrics_value["utilization.encoder"]="$encoder"
        gpu_metrics_value["clocks.current.graphics"]="$clocks_graphics"
        gpu_metrics_value["clocks.current.memory"]="$clocks_memory"

        apply_dictionary_value_format gpu_metrics_formatted gpu_metrics_value gpu_metrics_fmt
        update_threshold alerts gpu_metrics_value gpu_metrics_alert_treshold

        mod_draw \
            "$name" "$fan_speed" "$power_draw" "$memory_total" \
            "$memory_free" "$memory_used" "$gpu_utilization" "$temperature"\
            "$decoder" "$encoder" "$clocks_graphics" "$clocks_memory" > "$FIFO_FILE"


    done
}

mod_run
