#!/usr/bin/env bash

printf "Executing CAVA Output Plugin\n"

[ -f "$RESOURCE_FILE" ] && source "$RESOURCE_FILE"
: "${MODULE_CORE_DIR:=$(dirname $0)}"
. "$MODULE_CORE_DIR/functions"
: "${TMP_DIR:=/tmp}"

check_dependencies cava pactl

# shared cava
. "$MODULE_CORE_DIR/sc.functions"

cava_cfg="$TMP_DIR/cava_out.cfg"

g_sc_base_dzen2_bar_params=(-text 'Audio-Out')

mod_init_vars() {
    c_framerate=15
    c_bars=30
    c_fn_create_file="default_create_config"
}

mod_init_dzen2_vars() {
    c_bars=30
    c_padding=1
    c_height=$((CFG_HEIGHT - 2 * c_padding))
    c_additional_bar_params=(-fg_colors "<BAR4>")
}

default_create_config() {
    local config="$1"
    cat << EOF > "$config"
[general]
bars = $c_bars
sleep_timer = 1
framerate = $c_framerate

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = $c_height

channels = mono
mono_option = average

[smoothing]
noise_reduction = 20
EOF

    printf "Cava is configured with
. FPS: %15i
. Bars: %14i\n" "$c_framerate" "$c_bars"
}

mod_loop() {
    sc_run_cava_and_print_to_file "$cava_cfg" "$FIFO_FILE"
}

mod_run
