#!/usr/bin/env bash

printf "Executing CAVA Input Plugin\n"

[ -f "$RESOURCE_FILE" ] && source "$RESOURCE_FILE"
: "${MODULE_CORE_DIR:=$(dirname $0)}"
. "$MODULE_CORE_DIR/functions"
: "${TMP_DIR:=/tmp}"

check_dependencies cava

# shared cava code
. "$MODULE_CORE_DIR/sc.functions"

cava_cfg="$TMP_DIR/cava_in.cfg"

mod_init_vars() {
    sc_sensitivity=4400
    sc_framerate=15
    sc_bars=30
    sc_fn_create_file="default_create_config"
}

mod_init_dzen2_vars() {
    sc_bars=30
    sc_padding=1
    sc_height=$((CFG_HEIGHT - 2 * sc_padding))
    sc_additional_bar_params=(-text "Mic")
}

default_create_config() {
    local config="$1"

    check_dependencies pactl

    default_source=$(pactl info | grep "Default Source" | cut -d ' ' -f3)

    cat << EOF > "$config"
[general]
bars = $sc_bars
sleep_timer = 1
framerate = $sc_framerate
autosens = 0
sensitivity = $sc_sensitivity

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = $sc_height
mono_option = average
channels = mono
mono_option = average

[input]
method = pulse
source = "$default_source"

[smoothing]
noise_reduction = 15

EOF

    printf "Cava is configured with
. FPS: %15i
. Bars: %14i
. Sensitivity: %7i
. Source: %s\n" "$sc_framerate" "$sc_bars" "$sc_sensitivity" "$default_source"
}

mod_loop() {
    sc_run_cava_and_print_to_file "$cava_cfg" "$FIFO_FILE"
}

mod_run
