#!/usr/bin/env bash

printf "Executing XKeyboard Plugin\n"

[ -f "$RESOURCE_FILE" ] && source "$RESOURCE_FILE"
: "${MODULE_CORE_DIR:=$(dirname $0)}"
. "$MODULE_CORE_DIR/functions"
: "${TMP_DIR:=/tmp}"

check_dependencies nolifebar-kbd xkb-switch

declare -gA c_metrics_formatted
declare -gA c_metrics

mod_init_vars() {
    # Used for dzen2 draw
    c_visible_metrics=('capslock' 'numlock')
    c_metrics_formatted=(
        ["capslock"]="Capslock"
        ["numlock"]="Numlock"
    )
    c_additional_render_params=()
}


mod_draw_default() {
    local -n ref_var="$1"

    local layout="${c_metrics["layout"]}"
    local layout_short="${layout:0:3}"
    local capslock="${c_metrics["capslock"]}"
    local capslock_str=""
    if [[ $capslock == ON ]]; then capslock_str=" Caps Lock "; fi
    ref_var="${layout_short}${capslock_str}"
}

mod_draw_dzen2() {
    local -n ref_var="$1"
    local layout="${c_metrics["layout"]}"
    local layout_short="${layout:0:3}"

    local widget
    dzen2_draw_flags widget \
        c_metrics_formatted \
        c_metrics \
        c_visible_metrics \
        -label "$layout_short" \
        "${CFG_DEFAULT_DRAW_FLAG_PARAMS[@]}" \
        -label_highlight 0 \
        -name_size 60 \
        -flag_align _CENTER \
        -flag_x_padding 3 \
        "${c_additional_render_params[@]}"

    ref_var="^ca(1, xkb-switch -n)$widget^ca()"
}

mod_loop() {
    nolifebar-kbd | while IFS= read -r line; do
        if [[ $line == Layout:* ]]; then
            c_metrics["layout"]="${line#Layout: }"
        fi
        # nolifebar-kbd returns ON / OFF for caps/num locks
        if [[ $line == Caps\ Lock:* ]]; then
            c_metrics["capslock"]="${line#Caps Lock: }"
        fi
        if [[ $line == Num\ Lock:* ]]; then
            c_metrics["numlock"]="${line#Num Lock: }"
        fi

        if [[ -z "$line" ]]; then
            local output
            mod_draw output
            printf "%s\n" "$output" > "$FIFO_FILE"
        fi
    done
}

mod_run
