#!/usr/bin/env bash

THEMES=(THEME_CATPPUCCIN_LATTE THEME_CATPPUCCIN_FRAPPE THEME_CATPPUCCIN_MACCHIATO THEME_CATPPUCCIN_MOCHA THEME_NORD)

_CATPPUCCIN_DEFAULT_STYLES="
# Catppuccin default styles
<FG>   : <Text>
<BG>   : <Base>

<BAR1> : <Red>
<BAR2> : <Green>
<BAR3> : <Mauve>
<BAR4> : <Yellow>

<POPUP_FN_BIG>   : Terminus-14
<POPUP_FN>       : Terminus-12
<POPUP_FN_SMALL> : Terminus-8
<POPUP_FG>       : <FG>
<POPUP_BG>       : <BG>

<POPUP_BAR1> : <BAR1>
<POPUP_BAR2> : <BAR2>
<POPUP_BAR3> : <BAR3>
<POPUP_BAR4> : <BAR4>

<WIDGET_BG>        : <Surface0>
<WIDGET_TEXT_FG>   : <Surface2>
<WIDGET_TEXT_FN>   : <FN_2_ROWS>
<WIDGET_BORDER>    : <Overlay1>
<WIDGET_INACTIVE>  : <Overlay0>
<WIDGET_ACTIVE>    : <Green>
<WIDGET_FLAG_FG>   : <FG>
<WIDGET_FLAG_BG>   : <BG>

# xworkspaces mod: default render commands
<DZEN_WS_NO_WIN>       : ^fg(<Surface1>)^bg(<BG>)
<DZEN_WS_WITH_WIN>     : ^fg(<FG>)^bg(<BG>)
<DZEN_WS_CUR_NO_WIN>   : ^fg(<Surface1>)^bg(<Blue>)
<DZEN_WS_CUR_WITH_WIN> : ^fg(<BG>)^bg(<Blue>)
<DZEN_WS_URGENT>       : ^fg(<BG>)^bg(<Red>)

<FN_MAIN>    : Terminus:size=14:style=Light
<FN_MEDIUM>  : Terminus:size=10:style=Light
<FN_2_ROWS>  : Terminus-8
"

THEME_CATPPUCCIN_LATTE="
# Latte palette
<Rosewater> : #dc8a78
<Flamingo> : #dd7878
<Pink> : #ea76cb
<Mauve> : #8839ef
<Red> : #d20f39
<Maroon> : #e64553
<Peach> : #fe640b
<Yellow> : #df8e1d
<Green> : #40a02b
<Teal> : #179299
<Sky> : #04a5e5
<Sapphire> : #209fb5
<Blue> : #1e66f5
<Lavender> : #7287fd
<Text> : #4c4f69
<Subtext1> : #5c5f77
<Subtext0> : #6c6f85
<Overlay2> : #7c7f93
<Overlay1> : #8c8fa1
<Overlay0> : #9ca0b0
<Surface2> : #acb0be
<Surface1> : #bcc0cc
<Surface0> : #ccd0da

<Base> : #eff1f5
<Mantle> : #e6e9ef
<Crust> : #dce0e8

${_CATPPUCCIN_DEFAULT_STYLES}
"

THEME_CATPPUCCIN_FRAPPE="
# Frappe palette
<Rosewater> : #f2d5cf
<Flamingo> : #eebebe
<Pink> : #f4b8e4
<Mauve> : #ca9ee6
<Red> : #e78284
<Maroon> : #ea999c
<Peach> : #ef9f76
<Yellow> : #e5c890
<Green> : #a6d189
<Teal> : #81c8be
<Sky> : #99d1db
<Sapphire> : #85c1dc
<Blue> : #8caaee
<Lavender> : #babbf1
<Text> : #c6d0f5
<Subtext1> : #b5bfe2
<Subtext0> : #a5adce
<Overlay2> : #949cbb
<Overlay1> : #838ba7
<Overlay0> : #737994
<Surface2> : #626880
<Surface1> : #51576d
<Surface0> : #414559

<Base> : #303446
<Mantle> : #292c3c
<Crust> : #232634

${_CATPPUCCIN_DEFAULT_STYLES}
"

THEME_CATPPUCCIN_MACCHIATO="
# Macchiato palette
<Rosewater> : #f4dbd6
<Flamingo> : #f0c6c6
<Pink> : #f5bde6
<Mauve> : #c6a0f6
<Red> : #ed8796
<Maroon> : #ee99a0
<Peach> : #f5a97f
<Yellow> : #eed49f
<Green> : #a6da95
<Teal> : #8bd5ca
<Sky> : #91d7e3
<Sapphire> : #7dc4e4
<Blue> : #8aadf4
<Lavender> : #b7bdf8
<Text> : #cad3f5
<Subtext1> : #b8c0e0
<Subtext0> : #a5adcb
<Overlay2> : #939ab7
<Overlay1> : #8087a2
<Overlay0> : #6e738d
<Surface2> : #5b6078
<Surface1> : #494d64
<Surface0> : #363a4f

<Base> : #24273a
<Mantle> : #1e2030
<Crust> : #181926

${_CATPPUCCIN_DEFAULT_STYLES}
"

THEME_CATPPUCCIN_MOCHA="
# Mocha palette
<Rosewater> : #f5e0dc
<Flamingo> : #f2cdcd
<Pink> : #f5c2e7
<Mauve> : #cba6f7
<Red> : #f38ba8
<Maroon> : #eba0ac
<Peach> : #fab387
<Yellow> : #f9e2af
<Green> : #a6e3a1
<Teal> : #94e2d5
<Sky> : #89dceb
<Sapphire> : #74c7ec
<Blue> : #89b4fa
<Lavender> : #b4befe
<Text> : #cdd6f4
<Subtext1> : #bac2de
<Subtext0> : #a6adc8
<Overlay2> : #9399b2
<Overlay1> : #7f849c
<Overlay0> : #6c7086
<Surface2> : #585b70
<Surface1> : #45475a
<Surface0> : #313244

<Base> : #1e1e2e
<Mantle> : #181825
<Crust> : #11111b

${_CATPPUCCIN_DEFAULT_STYLES}
"

THEME_NORD="
# Nord palette:
# Polar Night
<nord0> : #2E3440
<nord1> : #3B4252
<nord2> : #434C5E
<nord3> : #4C566A

# Snow Storm
<snow1> : #D8DEE9
<snow2> : #E5E9F0
<snow3> : #ECEFF4

# Frost
<frost1> : #8FBCBB
<frost2> : #88C0D0
<frost3> : #81A1C1
<frost4> : #5E81AC

# Aurora
<auroraRed> : #BF616A
<auroraOrange> : #D08770
<auroraYellow> : #EBCB8B
<auroraGreen> : #A3BE8C
<auroraCyan> : #B48EAD

# Replacements:
<FG>   : <snow1>
<BG>   : <nord0>

<BAR1> : <auroraRed>
<BAR2> : <auroraGreen>
<BAR3> : <auroraCyan>
<BAR4> : <auroraYellow>

<POPUP_FN_BIG>   : Terminus-14
<POPUP_FN>       : Terminus-12
<POPUP_FN_SMALL> : Terminus-8
<POPUP_FG>       : <FG>
<POPUP_BG>       : <BG>

<POPUP_BAR1> : <BAR1>
<POPUP_BAR2> : <BAR2>
<POPUP_BAR3> : <BAR3>
<POPUP_BAR4> : <BAR4>

<WIDGET_BG>        : <nord1>
<WIDGET_TEXT_FG>   : <nord3>
<WIDGET_TEXT_FN>   : <FN_2_ROWS>
<WIDGET_BORDER>    : <nord3>
<WIDGET_INACTIVE>  : <nord3>
<WIDGET_ACTIVE>    : <auroraGreen>
<WIDGET_FLAG_FG>   : <FG>
<WIDGET_FLAG_BG>   : <BG>

# xworkspaces mod: default render commands
<DZEN_WS_NO_WIN>       : ^fg(<nord2>)^bg(<BG>)
<DZEN_WS_WITH_WIN>     : ^fg(<snow2>)^bg(<BG>)
<DZEN_WS_CUR_NO_WIN>   : ^fg(<nord3>)^bg(<frost4>)
<DZEN_WS_CUR_WITH_WIN> : ^fg(<FG>)^bg(<frost4>)
<DZEN_WS_URGENT>       : ^fg(<FG>)^bg(<auroraRed>)

<FN_MAIN>    : Terminus:size=14:style=Light
<FN_MEDIUM>  : Terminus:size=10:style=Light
<FN_2_ROWS>  : Terminus-8
"

THEME_MIRROR_EDGE="
<FN_MAIN>    : Terminus:size=14:style=Light
<FN_MEDIUM>  : Terminus:size=10:style=Light
<FN_2_ROWS>  : Terminus-8

<FG>   : #222
<BG>   : #ffffff

<BAR1> : #ff5c04
<BAR2> : #00cd00
<BAR3> : #0d34c1
<BAR4> : #cd853f

<POPUP_FN_BIG>   : Terminus-14
<POPUP_FN>       : Terminus-12
<POPUP_FN_SMALL> : Terminus-8

<POPUP_BAR1> : <BAR1>
<POPUP_BAR2> : <BAR2>
<POPUP_BAR3> : <BAR3>
<POPUP_BAR4> : <BAR4>

<POPUP_FG>   : <FG>
<POPUP_BG>   : <BG>
<WIDGET_BG>        : #efefef
<WIDGET_TEXT_FG>   : #ddd
<WIDGET_TEXT_FN>   : <FN_2_ROWS>
<WIDGET_BORDER>    : #444
<WIDGET_INACTIVE>  : #444
<WIDGET_ACTIVE>    : #ff5c04
<WIDGET_FLAG_FG>   : <FG>
<WIDGET_FLAG_BG>   : <BG>


# xworkspaces mod: default render commands
<DZEN_WS_NO_WIN>       : ^fg(#ddd)^bg(<BG>)
<DZEN_WS_WITH_WIN>     : ^fg(<FG>)^bg(<BG>)
<DZEN_WS_CUR_NO_WIN>   : ^fg(#ddd)^bg(#ff5c04)
<DZEN_WS_CUR_WITH_WIN> : ^fg(<FG>)^bg(#ff5c04)
<DZEN_WS_URGENT>       : ^fg(<BG>)^bg(#fd1111)
"
