# Data files for nolifebar
nolifebardir = $(prefix)/share/nolifebar

dist_nolifebar_DATA = \
	vol20a.xbm \
	vol20a.xpm \
	vol20b.xbm \
	vol20muteda.xbm \
	vol20mutedb.xbm

# Battery icons subdirectories
batteryoffdir = $(nolifebardir)/battery/off
dist_batteryoff_DATA = \
	battery/off/battery_off_0.xpm \
	battery/off/battery_off_1.xpm \
	battery/off/battery_off_2.xpm \
	battery/off/battery_off_3.xpm \
	battery/off/battery_off_4.xpm \
	battery/off/battery_off_5.xpm \
	battery/off/battery_off_6.xpm \
	battery/off/battery_off_7.xpm \
	battery/off/battery_off_8.xpm

batteryondir = $(nolifebardir)/battery/on
dist_batteryon_DATA = \
	battery/on/battery_on_0.xpm \
	battery/on/battery_on_1.xpm \
	battery/on/battery_on_2.xpm \
	battery/on/battery_on_3.xpm \
	battery/on/battery_on_4.xpm \
	battery/on/battery_on_5.xpm \
	battery/on/battery_on_6.xpm \
	battery/on/battery_on_7.xpm \
	battery/on/battery_on_8.xpm
