#!/usr/bin/env bash

echo "Executing Time Plugin"

: "${MODULE_CORE_DIR:=$(dirname $0)}"
source "$MODULE_CORE_DIR/functions"

show_short=0
handle_signal() {
 echo "Signal received: show_short=${show_short}"
 show_short=$((show_short ? 0 : 1))
}

trap 'handle_signal' SIGUSR1

mod_draw_dzen2() {
    local time_format="$1"
    printf "^ca(1, kill -SIGUSR1 $$)${time_format}^ca()\n" -1
}

mod_loop() {
    while true; do
        if ((show_short == 0)); then
            mod_draw "%(%H:%M)T" > "$FIFO_FILE"
            read_sleep 1
        else
            mod_draw '%(%Y-%m-%d %H:%M %S)T' > "$FIFO_FILE"
            read_sleep 0.5
            mod_draw '%(%Y-%m-%d %H:%M:%S)T' > "$FIFO_FILE"
            read_sleep 0.5
        fi
    done
}

mod_run
