name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout source code
      uses: actions/checkout@v4

    # Step 2: Restore apt cache
    - name: Restore APT Cache
      uses: awalsh128/cache-apt-pkgs-action@v1.4.3
      with:
        packages: autoconf automake libtool pkg-config libpulse-dev libx11-dev libxft-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev
        version: 1.1

    # Step 3: Generate the configure script
    - name: Generate configure script
      run: autoreconf -vif

    # Step 4: Run configure
    - name: Configure the project
      run: ./configure

    # Step 5: Build the project
    - name: Build the project
      run: make

    # Step 6: Run the tests (assuming tests are defined in your Makefile)
    - name: Run tests
      run: make test
